### ISSUE TITLE
KeyError: 'policy_assignment'

### ISSUE THREAD

**Issue by ewanlee** [YuhangSong/Arena-Baselines#1]
First of all, thank you very much for release this excellent project.
When I ran the first test case, I encountered the following problem:

![image](https://user-images.githubusercontent.com/11542337/71705911-c0fd2900-2e1c-11ea-95ec-d9e872a3ed36.png)

How can I resolve this bug?

**Comment by YuhangSong** [comment]
Thanks for letting me know. The bug is now fixed in the recent commit.

**Comment by YuhangSong** [comment]
Feel free to let me know (or re-open this issue) if you find further difficulties.

**Comment by ewanlee** [comment]
Thank you very much.
