### ISSUE TITLE
object does not fit in the plasma store

### ISSUE THREAD

**Issue by YuhangSong** [YuhangSong/Arena-Baselines#10]
This issue is solved by:

- change the train_batch_size parameter to be smaller.

**Comment by kimbring2** [comment]
Every PC have different memory. Thus, some error related with memory can be occured when you try to train a agent. 
![plasma_error](https://user-images.githubusercontent.com/11064407/73905121-a1f12b80-48e1-11ea-81a7-eee76b406a26.png)

When you meet that error, you need to decrease a train_batch_size to smaller.
![train_batch_size_mark](https://user-images.githubusercontent.com/11064407/73905374-6dca3a80-48e2-11ea-8aee-c875d8ec2d17.png)

Futhermore, an object_store_memory arguemnt of ray_init at a train.py file in Arena-Baselines folder must be set to proper value. Below is setting for my PC.
![ray_init](https://user-images.githubusercontent.com/11064407/73905456-aff37c00-48e2-11ea-8849-57a50fde6e61.png)

**Comment by YuhangSong** [comment]
Thank you for helping out, Kim.

**Comment by kimbring2** [comment]
Welcome. I need to check performance of my trained agent now.
