### ISSUE TITLE
TuneError: Insufficient cluster resources to launch trial

### ISSUE THREAD

**Issue by Chengzhi-Shen** [YuhangSong/Arena-Baselines#17]
Hi, I'm new to the Arena-Baselines.

I followed the Dependencies but when I first tried to run:
`python train.py -f ./arena-experiments/Arena-Benchmark.yaml`

I got the returned error:
> ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 11 CPUs, 1 GPUs but the cluster has only 4 CPUs, 1 GPUs, 1.37 GiB heap, 0.44 GiB objects. Pass `queue_trials=True` in ray.tune.run() or on the command line to queue trials until the cluster scales up. 
> 
> You can adjust the resource requests of RLlib agents by setting `num_workers`, `num_gpus`, and other configs. See the DEFAULT_CONFIG defined by each agent for more info.
> 

I did try to adjust the `queue_trials` but the same error still occurs . Any idea of how to solve this problem?

Thanks in advance.

**Comment by YuhangSong** [comment]
You probably want to learn more about ray. The short answer is that you do not have enough cpus,  change ```num_workers: 10``` to ```num_workers: 3``` should do the work.

**Comment by Chengzhi-Shen** [comment]
Thank you a lot.
